#!/usr/bin/env python3
"""Generate reproducible half-degree fixed-point sine values for both targets."""
import math
from pathlib import Path
root=Path(__file__).resolve().parents[1]
values=[round(math.sin(i*math.tau/720)*16384) for i in range(720)]
rows=[','.join(map(str,values[i:i+12])) for i in range(0,720,12)]
(root/'watchface/src/c/trig.h').write_text('#pragma once\n#include <stdint.h>\n/* Generated by execution/generate_trig.py. Scale 16384. */\nstatic const int16_t face_sine[720]={\n'+',\n'.join(rows)+'\n};\n')
