#!/usr/bin/env python3
"""Rasterize cached Natural Earth 110m polygons to a tiny 360x180 land mask."""
import hashlib
import json
import math
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
SOURCE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_110m_land.geojson'

def main():
    source = ROOT / 'data/ne_110m_land.geojson'
    if not source.exists():
        with urlopen(SOURCE, timeout=30) as response:
            source.write_bytes(response.read())
    bits = bytearray(8100)
    for feature in json.loads(source.read_text())['features']:
        geometry = feature['geometry']
        polygons = [geometry['coordinates']] if geometry['type'] == 'Polygon' else geometry['coordinates']
        for rings in polygons:
            for y in range(180):
                lat = 89.5 - y
                crossings = []
                for ring in rings:
                    for a, b in zip(ring, ring[1:]):
                        if (a[1] > lat) != (b[1] > lat):
                            crossings.append(a[0] + (lat-a[1])*(b[0]-a[0])/(b[1]-a[1]))
                crossings.sort()
                for left, right in zip(crossings[::2], crossings[1::2]):
                    for x in range(max(0, math.ceil(left+179.5)), min(360, math.ceil(right+179.5))):
                        i = y*360+x
                        bits[i//8] |= 1 << (i%8)
    rows = [','.join(str(v) for v in bits[i:i+32]) for i in range(0,len(bits),32)]
    (ROOT/'watchface/src/c/land.h').write_text('/* Natural Earth 5.1.2, public domain; generated by execution/generate_land.py. */\nstatic const unsigned char earth_land[8100]={\n'+',\n'.join(rows)+'\n};\n')
    (ROOT/'data/land-source.json').write_text(json.dumps({'url':SOURCE,'license':'Public domain','sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'resolution':'360x180, pixel-center sampling'},indent=2)+'\n')
    print('Generated 8100-byte land mask')

if __name__ == '__main__':
    main()
