#!/usr/bin/env python3
"""Append the full Pebble palette after stable legacy renderer indices."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def main():
    rows = ['/* Generated by execution/generate_colors.py; indices 10..73. */']
    for r in range(4):
        for g in range(4):
            for b in range(4):
                rows.append(f'{{{r*85},{g*85},{b*85}}},')
    (ROOT/'watchface/src/c/colors.inc').write_text('\n'.join(rows)+'\n')
if __name__ == '__main__': main()
