#pragma once
/* Which edition this source builds. The local wscript passes -DTAH_EDITION from
 * execution/build_editions.py, which takes precedence. CloudPebble generates its own wscript
 * and reads this file: main builds 0 (Origin), and each edition-* branch sets its own value
 * (generated by execution/publish_edition_branches.py). */
#ifndef TAH_EDITION
#define TAH_EDITION 1
#endif
